### ISSUE TITLE
Is webrtc (adapter-latest.js) a dependency for WebAudioTrack?

### ISSUE THREAD

**Issue by Jaikant** [danielstorey/WebAudioTrack#6]
@danielstorey This library is brilliant! 
 
Just a quick doubt, in the index.html we have the below script tag, is it really needed?

```
 <script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>
```

**Comment by jsalsman** [comment]
@Jaikant I just tried it without that script on OSX Safari 12 and Chrome latest, and on Android Chrome, and it worked fine. Since there aren't any script errors that I could see, I'm guessing it's no longer used. Someone should try it on iOS Safari etc. and Firefox?

**Comment by danielstorey** [comment]
Thanks guys. You'll probably find that most devices/browsers work without the above script. However if you look at the repo you'll see that it's provided as a shim to insulate apps from spec changes and prefix differences so it's probably best to leave it in - just in case any changes in the future with any new releases.

That being said, I noticed that I was linking to the fork instead of the original. I have updated the link and included it in the js module so there is now no need for you to include manually in your html.
